apiVersion: argoproj.io/v1alpha1
kind: Application
project: default
metadata:
  namespace: pacman-argo
spec:
  source:
    repoURL: https://github.com/OleksiiPasichnyk/pacman_argo_deployment.git
    targetRevision: HEAD
    path: "yaml configs"
  destination:
    server: https://kubernetes.default.svc
    namespace: pacman-argo
  project: default
  syncPolicy:
    manual: true
    syncOptions:
      - CreateNamespace=true